name: Reusable deployment workflow

on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
    secrets:
      AZURE_WEBAPP_SERVICE_NAME:
        required: true
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true
      AZURE_WEBAPP_SERVICE_NAME_PROD:
        required: true
      AZURE_WEBAPP_PUBLISH_PROFILE_PROD:
        required: true



jobs:
  deploy:
    name: Deploy to ${{ inputs.target-env }}
    permissions:
      contents: none
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.target-env }}
      # url: ${{ steps.step_id.outputs.url_output }}

    steps:
      - run: echo "🎉 target evn ${{ inputs.target-env}}"
      - run: echo "🎉 target evn inputs.target-env"
      - run: echo "💡 get azure webapp name from variables ${{ vars.AZURE_WEBAPP_SERVICE_NAME }}"
      - run: echo "🍏 is Dev  ${{ inputs.target-env }} == 'staging'"
      - run: echo "🐧 is Prod  ${{ inputs.target-env }} == 'production'"

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: unzip artifact for deployment
        run: unzip release.zip

      - name: "Deploy to Azure Dev WebApp"
        if:  inputs.target-env == 'staging'
        id: deploy-to-webapp-dev
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_SERVICE_NAME }}
          slot-name: "staging"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'

      - name: "Deploy to Azure Prod WebApp"
        if:  inputs.target-env == 'production'
        id: deploy-to-webapp-prod
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_SERVICE_NAME_PROD }}
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          package: '.'
